/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package googleform;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;

import io.github.bonigarcia.wdm.WebDriverManager;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws InterruptedException {
        System.out.println(new App().getGreeting());
        // System.setProperty("webdriver.chrome.driver","");
        WebDriverManager.chromedriver().setup();
        WebDriver driver = new ChromeDriver();
        driver.manage().window().maximize();
        driver.get("https://forms.gle/wjPkzeSEk1CM7KgGA");

        Thread.sleep(1000);
        WebElement inputName= driver.findElement(By.xpath("//div[@jsname='YPqjbf']/div[1]/div[1]/div/input"));
        inputName.sendKeys("pooja verma");

        WebElement textArea = driver.findElement(By.xpath("//textarea[@jsname='YPqjbf']"));
        textArea.sendKeys("I want to be the best QA Engineer! 1710572021");

        WebElement radioBox = driver.findElement(By.xpath("//div[@id='i13']/div[3]"));
        radioBox.click();

        Thread.sleep(1000);
        WebElement checkBox = driver.findElement(By.xpath("//div[@id='i30']/div[2]"));
        checkBox.click();
       
        WebElement dropDown = driver.findElement(By.xpath("//div[@jscontroller='liFoG']/div[1]/div[1]/div[2]"));
        dropDown.click();
        Thread.sleep(1000);
        WebElement selectValue = driver.findElement(By.xpath("//*[@id='mG61Hd']/div[2]/div/div[2]/div[5]/div/div/div[2]/div/div[2]/div[5]"));
        selectValue.click();
       

        Thread.sleep(1000);
        WebElement date = driver.findElement(By.xpath("//*[@id='mG61Hd']/div[2]/div/div[2]/div[6]/div/div/div[2]/div/div/div[2]/div[1]/div/div[1]/input"));
        date.sendKeys("02-04-2024");;
        Thread.sleep(1000);
        WebElement selectTimeHrs = driver.findElement(By.xpath("//div[@class='RH5hzf RLS9Fe']/div[1]/div[2]/div[7]/div/div/div[2]/div/div[1]/div[2]/div[1]/div[1]/div[1]/input"));
        selectTimeHrs.sendKeys("9");
        WebElement selectTimeMin = driver.findElement(By.xpath("//div[@class='RH5hzf RLS9Fe']/div[1]/div[2]/div[7]/div[1]/div[1]/div[2]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/input"));
        selectTimeMin.sendKeys("00");
        Thread.sleep(1000);

        WebElement submtBtn = driver.findElement(By.xpath("//span[text()='Submit']"));
        submtBtn.click();
       
    }
}
